### ISSUE TITLE
Errors are printed to the console

### ISSUE THREAD

**Issue by emmercm** [enten/cmpro-dat#2]
I'd rather be in control of printing exception messages to the console myself:

https://github.com/enten/cmpro-dat/blob/f285cea14090177630e14416dc1dbe3b6c6a26fb/src/cmpro-dat.ts#L363

**Comment by enten** [comment]
[cmpro-dat@0.0.3](https://www.npmjs.com/package/cmpro-dat/v/0.0.3) was released and [add option `printCodeSnippetOnError`](https://github.com/enten/cmpro-dat/commit/986e6c675aa06ae8cb4cb13531f47188017e745e).

Option `printCodeSnippetOnError` is defaults to `true` and can be used to hide print of code snippet on error with `false` (see example below).

_Can we close this issue?_

Example:

```ts
const readStream = fs.createReadStream('./Sony - PlayStation - BIOS Datfile (24) (2016-10-21).dat', 'utf8');
const datParsePromise = DAT.parse(readStream, { printCodeSnippetOnError: false });
```

**Comment by emmercm** [comment]
I believe so, thank you @enten !
